db:
  name: database
  app: database
  replicaCount: 1
  container:
    name: db
    image: postgres:15
    imagePullPolicy: IfNotPresent
    port: 5432
  pvc:
    name: postgres-pvc
    storage: 1Gi
  env:
    POSTGRES_USER: "yourusername"
    POSTGRES_PASSWORD: "yourpassword"
    POSTGRES_DB: "YourDatabaseName"
    HOST: "postgresql"
  resources:
    limits:
      cpu: 1000m
      ephemeralStorage: 1000Mi
      memory: 1000Mi
    requests:
      cpu: 1000m
      ephemeralStorage: 1000Mi
      memory: 1000Mi
  service:
    name: postgresql
    type: ClusterIP
    port: 5432
    targetPort: 5432

angular:
  name: angular
  app: angular
  replicaCount: 1
  container:
    name: angular
    image: mohammadsadeghmontazeri/starfront:v0.12.1
    imagePullPolicy: Always
    port: 4000
  resources:
    limits:
      cpu: 1000m
      ephemeralStorage: 1000Mi
      memory: 1000Mi
    requests:
      cpu: 1000m
      ephemeralStorage: 1000Mi
      memory: 1000Mi
  service:
    name: angular-service
    type: NodePort
    port: 4000
    targetPort: 4000
    nodePort: 30081

webApp:
  name: web-app
  app: web-app
  replicaCount: 1
  container:
    name: web-app
    image: mohammadsadeghmontazeri/starback:v0.15.1-dev.3
    imagePullPolicy: IfNotPresent
    port: 80
  initContainer:
    name: migrate-db
    image: mohammadsadeghmontazeri/migratestar:v0.15.1-dev.3
    imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      ephemeralStorage: 1000Mi
      memory: 1000Mi
    requests:
      cpu: 100m
      ephemeralStorage: 100Mi
      memory: 100Mi
  env:
    connectionString: "Host=postgresql;Database=YourDatabaseName;Username=yourusername;Password=yourpassword"
  service:
    name: web-app-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080
