apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.app }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.db.app }}
  serviceName: {{ .Values.db.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.app }}
    spec:
      containers:
        - name: {{ .Values.db.container.name }}
          image: {{ .Values.db.container.image }}
          imagePullPolicy: {{ .Values.db.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.db.container.port }}
          resources:
            limits:
              cpu: {{ .Values.db.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.db.resources.limits.ephemeralStorage }}
              memory: {{ .Values.db.resources.limits.memory }}
            requests:
              cpu: {{ .Values.db.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.db.resources.requests.ephemeralStorage }}
              memory: {{ .Values.db.resources.requests.memory }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: HOST
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
