apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  labels:
    app: {{ .Values.db.app }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
  selector:
    app: {{ .Values.db.app }}
