apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.secret.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.secret.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.db.secret.POSTGRES_DB | b64enc | quote }}
  HOST: {{ .Values.db.secret.HOST | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: web-app-secret
type: Opaque
data:
  connectionString: {{ .Values.webApp.secret.connectionString | b64enc | quote }}
  JWT_ISSUER: {{ .Values.webApp.secret.JWT_ISSUER | b64enc | quote }}
  JWT_AUDIENCE: {{ .Values.webApp.secret.JWT_AUDIENCE | b64enc | quote }}
  JWT_KEY: {{ .Values.webApp.secret.JWT_KEY | b64enc | quote }}
  ROOTUSER_ROLE: {{ .Values.webApp.secret.ROOTUSER_ROLE | b64enc | quote }}
  ROOTUSER_USERNAME: {{ .Values.webApp.secret.ROOTUSER_USERNAME | b64enc | quote }}
  ROOTUSER_EMAIL: {{ .Values.webApp.secret.ROOTUSER_EMAIL | b64enc | quote }}
  ROOTUSER_PASSWORD: {{ .Values.webApp.secret.ROOTUSER_PASSWORD | b64enc | quote }}