apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webApp.name }}
  labels:
    app: {{ .Values.webApp.app }}
spec:
  replicas: {{ .Values.webApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webApp.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.webApp.app }}
    spec:
      containers:
        - name: {{ .Values.webApp.container.name }}
          image: {{ .Values.webApp.container.image }}
          imagePullPolicy: {{ .Values.webApp.container.imagePullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.webApp.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.webApp.resources.limits.ephemeralStorage }}
              memory: {{ .Values.webApp.resources.limits.memory }}
            requests:
              cpu: {{ .Values.webApp.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.webApp.resources.requests.ephemeralStorage }}
              memory: {{ .Values.webApp.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.webApp.container.port }}
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: connectionString
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: JWT_ISSUER
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: JWT_AUDIENCE
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: JWT_KEY
            - name: ROOTUSER_ROLE
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: ROOTUSER_ROLE
            - name: ROOTUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: ROOTUSER_USERNAME
            - name: ROOTUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: ROOTUSER_EMAIL
            - name: ROOTUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: ROOTUSER_PASSWORD
      initContainers:
        - name: {{ .Values.webApp.initContainer.name }}
          image: {{ .Values.webApp.initContainer.image }}
          imagePullPolicy: {{ .Values.webApp.initContainer.imagePullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.webApp.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.webApp.resources.limits.ephemeralStorage }}
              memory: {{ .Values.webApp.resources.limits.memory }}
            requests:
              cpu: {{ .Values.webApp.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.webApp.resources.requests.ephemeralStorage }}
              memory: {{ .Values.webApp.resources.requests.memory }}
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: connectionString
